(function registerDominoLongTablePage(){
"use strict";
window.poveyProblemPages=window.poveyProblemPages||{};

const PROBLEM="17.2";
const QUESTION=Object.freeze({n:8});
const hints=Object.freeze([
  "Use T₀=1 for the empty board and T₁=1 for the single vertical domino.",
  "Look only at the first column of a 2×n board. If it is covered vertically, a 2×(n−1) board remains.",
  "If the top-left cell is covered horizontally, the bottom-left cell is forced into a second horizontal domino, leaving a 2×(n−2) board.",
  "Those cases are disjoint and exhaustive, so Tₙ=Tₙ₋₁+Tₙ₋₂.",
  "Starting 1,1 gives T₂=2, T₃=3, T₄=5, T₅=8, T₆=13, T₇=21 and T₈=34."
]);
const resetMarkup='<button class="ghost-button" type="button" data-problem-action="p172-reset">Reset</button>';
const initialState=()=>({n:QUESTION.n,orientation:"vertical",placements:[],nextDominoId:1,decompositionStep:0,exampleIndex:-1,placementMessage:"Choose an orientation, then tap an empty cell.",answer:"",feedback:"",feedbackTone:"neutral",committed:false,hintsUsed:0,revealed:false});
let state=initialState();
const tilingCache=new Map();

function clampInteger(value,min,max){return Math.max(min,Math.min(max,Math.round(Number(value))));}
function escapeAttribute(value){return String(value).replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function tilingCounts(n){const counts=[1];if(n>=1)counts.push(1);for(let index=2;index<=n;index+=1)counts.push(counts[index-1]+counts[index-2]);return counts;}
function enumerateTilings(n){if(tilingCache.has(n))return tilingCache.get(n).map((tiling)=>tiling.map((cells)=>[...cells]));if(n===0){tilingCache.set(0,[[]]);return[[]];}const occupied=Array(2*n).fill(false),results=[];function search(dominoes){const first=occupied.findIndex((value)=>!value);if(first===-1){results.push(dominoes.map((cells)=>[...cells]));return;}const row=Math.floor(first/n),column=first%n;if(row===0){const below=first+n;if(!occupied[below]){occupied[first]=occupied[below]=true;search([...dominoes,[first,below]]);occupied[first]=occupied[below]=false;}}if(column<n-1){const right=first+1;if(!occupied[right]){occupied[first]=occupied[right]=true;search([...dominoes,[first,right]]);occupied[first]=occupied[right]=false;}}}search([]);tilingCache.set(n,results);return results.map((tiling)=>tiling.map((cells)=>[...cells]));}
function placementOrientation(cells,n){return Math.abs(cells[0]-cells[1])===n?"vertical":"horizontal";}
function examplePlacements(n,index){const tilings=enumerateTilings(n),selected=tilings[((index%tilings.length)+tilings.length)%tilings.length];return selected.map((cells,placementIndex)=>({id:placementIndex+1,cells:[...cells],orientation:placementOrientation(cells,n)}));}
function occupiedCells(placements){return new Set(placements.flatMap((placement)=>placement.cells));}
function attemptPlacement(placements,n,cellIndex,orientation,nextId){const existing=placements.find((placement)=>placement.cells.includes(cellIndex));if(existing)return{placements:placements.filter((placement)=>placement.id!==existing.id),nextId,message:`Removed domino ${existing.id}.`,changed:true};const row=Math.floor(cellIndex/n),column=cellIndex%n,cells=orientation==="vertical"?[column,column+n]:[row*n+column,row*n+column+1];if(orientation==="horizontal"&&column>=n-1)return{placements,nextId,message:"A horizontal domino needs one more column to the right.",changed:false};const occupied=occupiedCells(placements);if(cells.some((cell)=>occupied.has(cell)))return{placements,nextId,message:"That domino would overlap an existing one.",changed:false};return{placements:[...placements,{id:nextId,cells,orientation}],nextId:nextId+1,message:`Placed ${orientation} domino ${nextId}.`,changed:true};}
function tilingValues(n=state.n){const counts=tilingCounts(n),total=counts[n],verticalBranch=n>=1?counts[n-1]:1,horizontalBranch=n>=2?counts[n-2]:0,enumerated=enumerateTilings(n).length;return{counts,total,verticalBranch,horizontalBranch,enumerated,recurrenceResidual:n>=2?total-verticalBranch-horizontalBranch:0,enumerationResidual:enumerated-total};}
const challenge=tilingValues(QUESTION.n);
function parseInteger(raw){const normalized=String(raw).trim().replace(/[\s,_]/g,"");return/^[-+]?\d+(?:\.0+)?$/.test(normalized)?Number(normalized):NaN;}

function boardMarkup(){const occupied=occupiedCells(state.placements),complete=occupied.size===2*state.n;return `<section class="p172-board-side" aria-labelledby="p172-board-heading"><div class="p172-board-heading"><div><span class="p172-kicker">MANUAL 2×${state.n} BOARD</span><h3 id="p172-board-heading">Build one valid tiling</h3></div><span>${state.placements.length} dominoes · ${occupied.size}/${2*state.n} cells</span></div><div class="p172-board" role="group" aria-label="Two row by ${state.n} column domino board. ${complete?"All cells are covered by a valid tiling.":`${2*state.n-occupied.size} cells remain empty.`}" style="--p172-columns:${state.n}">${Array.from({length:2*state.n},(_,cellIndex)=>{const row=Math.floor(cellIndex/state.n)+1,column=cellIndex%state.n+1,placement=state.placements.find((item)=>item.cells.includes(cellIndex));return placement?`<button class="p172-cell is-filled tone-${placement.id%4}" type="button" data-p172-cell="${cellIndex}" aria-label="Row ${row}, column ${column}, occupied by ${placement.orientation} domino ${placement.id}; activate to remove it"><span>${placement.id}</span></button>`:`<button class="p172-cell is-empty" type="button" data-p172-cell="${cellIndex}" aria-label="Empty cell, row ${row}, column ${column}; place a ${state.orientation} domino here"></button>`;}).join("")}</div><div class="p172-placement-status ${complete?"is-complete":""}" role="status"><strong>${complete?"Complete valid tiling":"Board in progress"}</strong><span>${complete?`One of ${tilingValues().total} possibilities.`:state.placementMessage}</span></div></section>`;}
function decompositionMarkup(){const values=tilingValues(),step=state.decompositionStep;if(state.n<2)return `<section class="p172-decomposition" aria-labelledby="p172-decomposition-heading"><span class="p172-kicker">FIRST-COLUMN DECOMPOSITION</span><h3 id="p172-decomposition-heading">Base case T${state.n}=1</h3><div class="p172-base-case">${state.n===0?"The empty board has one empty tiling.":"A 2×1 board accepts exactly one vertical domino."}</div><div class="p172-count-list">${values.counts.map((count,index)=>`<span class="${index===state.n?"is-current":""}">T${index}=${count}</span>`).join("")}</div></section>`;return `<section class="p172-decomposition" aria-labelledby="p172-decomposition-heading"><span class="p172-kicker">FIRST-COLUMN DECOMPOSITION · STEP ${step}/3</span><h3 id="p172-decomposition-heading">Exactly two possible beginnings</h3><p class="p172-decomposition-prompt">${step===0?"Inspect the top-left cell.":step===1?"Case A: cover the first column vertically.":step===2?"Case B: a top horizontal forces a bottom horizontal.":"Add the two disjoint branches."}</p><div class="p172-branches"><article class="p172-branch is-vertical ${step===1||step===3?"is-active":""}"><span>CASE A</span><div class="p172-mini-board"><i class="is-vertical"></i><b>2×${state.n-1}</b></div><p>One vertical first domino leaves T${state.n-1}=<strong>${values.verticalBranch}</strong> tilings.</p></article><article class="p172-branch is-horizontal ${step===2||step===3?"is-active":""}"><span>CASE B</span><div class="p172-mini-board"><i class="is-horizontal top"></i><i class="is-horizontal bottom"></i><b>2×${state.n-2}</b></div><p>Two forced horizontals leave T${state.n-2}=<strong>${values.horizontalBranch}</strong> tilings.</p></article></div><div class="p172-recurrence ${step===3?"is-active":""}"><span>DISJOINT + EXHAUSTIVE</span><strong>T${state.n}=T${state.n-1}+T${state.n-2}=${values.verticalBranch}+${values.horizontalBranch}=${values.total}</strong></div><div class="p172-count-list" aria-label="Tiling count recurrence list">${values.counts.map((count,index)=>`<span class="${index===state.n?"is-current":""}">T${index}=${count}</span>`).join("")}</div></section>`;}
function metricsMarkup(){const values=tilingValues();return `<div class="p172-metrics" aria-live="polite"><div><span>Total tilings T${state.n}</span><strong>${values.total}</strong><small>recurrence and enumeration agree</small></div><div><span>Vertical-first branch</span><strong>${values.verticalBranch}</strong><small>${state.n>=1?`T${state.n-1}`:"base case"}</small></div><div><span>Horizontal-pair branch</span><strong>${values.horizontalBranch}</strong><small>${state.n>=2?`T${state.n-2}`:"not available"}</small></div></div>`;}
function dynamicMarkup(){return `<div class="p172-dynamic"><div class="p172-lab">${boardMarkup()}${decompositionMarkup()}</div>${metricsMarkup()}</div>`;}
function controlsMarkup(){return `<section class="p172-controls" aria-label="Domino tiling controls"><label for="p172-n"><span>Table length n<output data-p172-live="n">${state.n}</output></span><input id="p172-n" data-p172-slider="n" type="range" min="1" max="12" step="1" value="${state.n}"/></label><div class="p172-control-rows"><div class="p172-orientation" role="group" aria-label="Domino placement orientation"><span>Place</span><button class="secondary-button ${state.orientation==="vertical"?"active":""}" type="button" data-problem-action="p172-orientation" data-p172-orientation="vertical" aria-pressed="${state.orientation==="vertical"}">Vertical</button><button class="secondary-button ${state.orientation==="horizontal"?"active":""}" type="button" data-problem-action="p172-orientation" data-p172-orientation="horizontal" aria-pressed="${state.orientation==="horizontal"}">Horizontal</button><button class="ghost-button" type="button" data-problem-action="p172-clear">Clear board</button><button class="ghost-button" type="button" data-problem-action="p172-example">Next valid tiling</button></div><div class="p172-decomposition-controls"><span>Decomposition <strong data-p172-decomposition-step>${state.decompositionStep}/3</strong></span><button class="secondary-button" type="button" data-problem-action="p172-decomposition-previous" ${state.decompositionStep<=0?"disabled":""}>Previous</button><button class="primary-button" type="button" data-problem-action="p172-decomposition-next" ${state.decompositionStep>=3||state.n<2?"disabled":""}>Next case</button></div></div></section>`;}
function feedbackMarkup(){return state.feedback?`<div class="p172-feedback is-${state.feedbackTone}" role="status">${state.feedback}</div>`:"";}
function hintsMarkup(){return state.hintsUsed?`<div class="hint-stack p172-hints" aria-live="polite">${hints.slice(0,state.hintsUsed).map((hint,index)=>`<div class="hint"><strong>Hint ${index+1}.</strong> ${hint}</div>`).join("")}</div>`:"";}
function solutionMarkup(){if(!state.revealed)return"";return `<section class="p172-solution" aria-labelledby="p172-solution-heading" aria-live="polite"><h3 id="p172-solution-heading">The first cell forces the recurrence</h3><div class="p172-equation">T₀=1, T₁=1</div><div class="p172-equation">vertical first domino → Tₙ₋₁ completions</div><div class="p172-equation">two horizontal first dominoes → Tₙ₋₂ completions</div><div class="p172-equation">Tₙ=Tₙ₋₁+Tₙ₋₂</div><div class="p172-equation is-answer">T₈: 1,1,2,3,5,8,13,21,34 ⇒ 34 tilings</div><p>The two cases cannot overlap and every tiling begins with one of them, so adding their counts neither misses nor double-counts a tiling.</p><p class="p172-limits"><strong>Model boundary.</strong> Dominoes cover exactly two orthogonally adjacent unit cells, may be vertical or horizontal, and cannot overlap or protrude. Reflections and rotations of a completed board are counted as distinct only when they occupy different cell pairs. T₀=1 is the empty completion needed to make the recurrence work at n=2.</p></section>`;}
function placementAudit(){const cells=state.placements.flatMap((placement)=>placement.cells),unique=new Set(cells);return{coveredCells:unique.size,duplicateCellCount:cells.length-unique.size,allDominoesAdjacent:state.placements.every((placement)=>{const [a,b]=placement.cells;return Math.abs(a-b)===state.n||Math.abs(a-b)===1&&Math.floor(a/state.n)===Math.floor(b/state.n);}),complete:unique.size===2*state.n&&cells.length===unique.size};}
function snapshot(){const values=tilingValues(),audit=placementAudit();return JSON.stringify({problem:PROBLEM,provenance:"Original extension created for this project; not present in Professor Povey's Perplexing Problems",model:"domino tilings of a two by n unit-cell board",n:state.n,baseCases:{T0:1,T1:1},recurrence:"T_n = T_(n-1) + T_(n-2)",countByRecurrence:values.total,countByEnumeration:values.enumerated,verticalFirstCount:values.verticalBranch,horizontalPairFirstCount:values.horizontalBranch,residuals:{recurrence:values.recurrenceResidual,enumeration:values.enumerationResidual},orientation:state.orientation,placements:state.placements,placementAudit:audit,decompositionStep:state.decompositionStep,exampleIndex:state.exampleIndex,challenge:{n:QUESTION.n,answer:challenge.total},answer:state.answer||null,committed:state.committed,hintsUsed:state.hintsUsed,solutionRevealed:state.revealed},null,2);}
function render(){return `<main class="book-shell p172-shell">${warning()}<header class="book-header"><div class="book-brand"><strong>Perplexing Problems</strong><span class="eyebrow">Original combinatorics extension</span></div><div class="book-progress">${problemProgress(PROBLEM)}</div>${problemHeaderActions(PROBLEM,resetMarkup)}</header><div class="book-spread p172-spread"><article class="book-page p172-problem-page"><div class="problem-number">Problem 17.2</div><h1 class="book-title p172-title">Dominoes at the Long Table</h1><div class="difficulty" aria-label="One star difficulty">★</div><p class="p172-extension-note">Original extension. This chapter and activity were created for this project and do not appear in Professor Povey’s Perplexing Problems.</p><p class="problem-copy">Cover a 2×n table of unit cells using 2×1 dominoes, with no gaps or overlaps.</p><p class="problem-copy">Show that Tₙ=Tₙ₋₁+Tₙ₋₂, then find the number of tilings when n=8.</p><section class="p172-model-card"><strong>Only the first column matters</strong><p>It begins with either one vertical domino or two forced horizontal dominoes. Those cases leave smaller copies of the same problem.</p></section><section class="prediction-box"><div class="eyebrow">Commit before enumerating</div><p>The counts begin 1,1,2,3,5. Continue the recurrence to the eight-column table.</p></section></article><section class="book-page book-stage p172-stage" aria-labelledby="p172-stage-title"><div class="p172-stage-heading"><div><span class="eyebrow">Domino recurrence laboratory</span><h2 id="p172-stage-title">Build locally; count recursively</h2></div><p>Place dominoes by hand or step through the two first-column branches. Exact enumeration checks the recurrence.</p></div>${dynamicMarkup()}${controlsMarkup()}</section><aside class="book-page book-coach p172-coach"><div class="coach-kicker">Solve the fixed challenge</div><p class="coach-question">How many complete tilings does a 2×8 board have?</p><form class="p172-answer-form" data-p172-answer-form novalidate><label for="p172-answer">Number of tilings T₈</label><div><input id="p172-answer" type="text" inputmode="numeric" autocomplete="off" value="${escapeAttribute(state.answer)}" placeholder="tilings"/><button class="primary-button" type="submit">Check</button></div></form>${feedbackMarkup()}<div class="button-row p172-help-row"><button class="secondary-button" type="button" data-problem-action="p172-hint" ${state.hintsUsed>=hints.length?"disabled":""}>${state.hintsUsed?"Another hint":"Give me a hint"}</button><button class="ghost-button" type="button" data-problem-action="p172-reveal" ${state.revealed?"disabled":""}>${state.revealed?"Solution revealed":"Reveal solution"}</button></div>${hintsMarkup()}${solutionMarkup()}<div class="p172-debug">${debugPanel("Development state",snapshot())}</div></aside></div>${problemNav(PROBLEM)}</main>`;}
function updateDynamicDom(root){const dynamic=root.querySelector(".p172-dynamic");if(dynamic)dynamic.outerHTML=dynamicMarkup();root.querySelectorAll('[data-p172-live="n"]').forEach((node)=>{node.textContent=String(state.n);});const slider=root.querySelector("#p172-n");if(slider){slider.value=String(state.n);slider.setAttribute("aria-valuetext",`Table length ${state.n}; ${tilingValues().total} complete tilings`);}root.querySelectorAll('[data-problem-action="p172-orientation"]').forEach((button)=>{const active=button.dataset.p172Orientation===state.orientation;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});root.querySelectorAll("[data-p172-decomposition-step]").forEach((node)=>{node.textContent=`${state.decompositionStep}/3`;});const previous=root.querySelector('[data-problem-action="p172-decomposition-previous"]'),next=root.querySelector('[data-problem-action="p172-decomposition-next"]');if(previous)previous.disabled=state.decompositionStep<=0;if(next)next.disabled=state.decompositionStep>=3||state.n<2;root.querySelectorAll(".state-surface").forEach((surface)=>{surface.textContent=snapshot();});}
function bindDynamic(root){root.querySelectorAll("[data-p172-cell]").forEach((cell)=>cell.addEventListener("click",()=>{const result=attemptPlacement(state.placements,state.n,Number(cell.dataset.p172Cell),state.orientation,state.nextDominoId);state.placements=result.placements;state.nextDominoId=result.nextId;state.placementMessage=result.message;state.exampleIndex=-1;state.feedback="";state.committed=false;updateDynamicDom(root);bindDynamic(root);}));}
function refreshDynamic(root){updateDynamicDom(root);bindDynamic(root);}
function renderAndFocus(rerender,selector){rerender();window.requestAnimationFrame(()=>document.querySelector(selector)?.focus());}
function bind({render:rerender}){
  const root=document.querySelector(".p172-shell");
  if(!root)return;
  bindDynamic(root);
  root.querySelector("[data-p172-slider]")?.addEventListener("input",(event)=>{
    state.n=clampInteger(event.target.value,1,12);
    state.placements=[];
    state.nextDominoId=1;
    state.decompositionStep=0;
    state.exampleIndex=-1;
    state.placementMessage="Choose an orientation, then tap an empty cell.";
    state.feedback="";
    state.committed=false;
    refreshDynamic(root);
  });
  root.querySelectorAll("[data-problem-action]").forEach((control)=>control.addEventListener("click",()=>{
    const action=control.dataset.problemAction;
    if(action==="p172-reset"){state=initialState();renderAndFocus(rerender,"#p172-n");return;}
    if(action==="p172-orientation"){state.orientation=control.dataset.p172Orientation;state.placementMessage=`${state.orientation[0].toUpperCase()+state.orientation.slice(1)} placement selected.`;refreshDynamic(root);return;}
    if(action==="p172-clear"){state.placements=[];state.nextDominoId=1;state.exampleIndex=-1;state.placementMessage="Board cleared.";refreshDynamic(root);return;}
    if(action==="p172-example"){const total=enumerateTilings(state.n).length;state.exampleIndex=(state.exampleIndex+1)%total;state.placements=examplePlacements(state.n,state.exampleIndex);state.nextDominoId=state.placements.length+1;state.placementMessage=`Showing valid tiling ${state.exampleIndex+1} of ${total}.`;refreshDynamic(root);return;}
    if(action==="p172-decomposition-previous"){state.decompositionStep=Math.max(0,state.decompositionStep-1);refreshDynamic(root);return;}
    if(action==="p172-decomposition-next"){state.decompositionStep=Math.min(3,state.decompositionStep+1);refreshDynamic(root);return;}
    if(action==="p172-hint")state.hintsUsed=Math.min(hints.length,state.hintsUsed+1);
    if(action==="p172-reveal")state.revealed=true;
    rerender();
  }));
  root.querySelector("#p172-answer")?.addEventListener("input",(event)=>{state.answer=event.target.value;state.feedback="";state.feedbackTone="neutral";});
  root.querySelector("[data-p172-answer-form]")?.addEventListener("submit",(event)=>{
    event.preventDefault();
    const raw=event.currentTarget.querySelector("#p172-answer")?.value||"",answer=parseInteger(raw);
    state.answer=raw.trim();
    state.committed=false;
    state.feedbackTone="neutral";
    if(!Number.isFinite(answer)||answer<0){state.feedback="Enter a non-negative whole number of tilings.";state.feedbackTone="warn";}
    else if(answer===challenge.total){state.feedback="Correct. The recurrence gives T₈=T₇+T₆=21+13=34 tilings.";state.feedbackTone="success";state.committed=true;state.n=QUESTION.n;state.placements=[];state.nextDominoId=1;state.exampleIndex=-1;state.decompositionStep=3;}
    else if(answer===21){state.feedback="Twenty-one is T₇. Add T₆=13 to advance one more column.";}
    else if(answer===55){state.feedback="Fifty-five is T₉. The challenge stops at eight columns.";}
    else{state.feedback="Start from T₀=T₁=1 and repeatedly add the previous two counts through T₈.";}
    renderAndFocus(rerender,"#p172-answer");
  });
}
window.poveyProblemPages[PROBLEM]={render,bind};
})();
