(function registerThreeLanternSwitchboardPage() {
  "use strict";

  window.poveyProblemPages = window.poveyProblemPages || {};

  const PROBLEM = "23.1";
  const SOLUTION = Object.freeze([4, 3, 5]);
  const FACTOR_OPTIONS = Object.freeze(["-3", "-2", "-1", "-1/2", "1/2", "1", "2", "3"]);
  const EXTENSION_DISCLOSURE = "Original extension. This chapter and activity were created for this project and do not appear in Professor Povey’s Perplexing Problems.";
  const stages = Object.freeze([
    Object.freeze({ short: "Encode", title: "Separate coefficients from variables", copy: "Each equation becomes one augmented-matrix row. The vertical bar separates the coefficient matrix from the constants; the variable order stays x, y, z." }),
    Object.freeze({ short: "Eliminate", title: "Use only reversible row operations", copy: "Swap rows, multiply a whole row by a non-zero number, or add a multiple of one row to another. These operations replace equations by equivalent equations." }),
    Object.freeze({ short: "Read", title: "Reduce until each row isolates one variable", copy: "At reduced row-echelon form, the left block is the identity and the augmented column reads x=4, y=3, z=5. Every intermediate plane triple has the same common intersection." }),
  ]);
  const hints = Object.freeze([
    "Use R₂←R₂−2R₁ to eliminate x from the second row.",
    "Use R₃←R₃−R₁ to eliminate x from the third row.",
    "Eliminate y between [0,−3,−1|−14] and [0,2,−3|−9]. This eventually gives a row proportional to [0,0,1|5].",
    "Back-substitution gives y=3 once z=5.",
    "The first equation then gives x=12−3−5=4.",
  ]);
  const resetMarkup = '<button class="ghost-button" type="button" data-problem-action="p231-reset">Reset</button>';

  function gcd(a, b) { let x = Math.abs(Math.trunc(a)), y = Math.abs(Math.trunc(b)); while (y) { const remainder = x % y; x = y; y = remainder; } return x || 1; }
  function fraction(numerator, denominator = 1) { if (denominator === 0) throw new Error("Zero denominator"); const sign = denominator < 0 ? -1 : 1, divisor = gcd(numerator, denominator); return Object.freeze({ n: sign * numerator / divisor, d: Math.abs(denominator) / divisor }); }
  function add(left, right) { return fraction(left.n * right.d + right.n * left.d, left.d * right.d); }
  function multiply(left, right) { return fraction(left.n * right.n, left.d * right.d); }
  function equal(left, right) { return left.n === right.n && left.d === right.d; }
  function numeric(value) { return value.n / value.d; }
  function fractionText(value) { if (value.n === 0) return "0"; return value.d === 1 ? String(value.n) : `${value.n}/${value.d}`; }
  function cloneMatrix(matrix) { return matrix.map((row) => row.map((value) => fraction(value.n, value.d))); }
  function initialMatrix() { return [[1,1,1,12],[2,-1,1,10],[1,3,-2,3]].map((row) => row.map((value) => fraction(value))); }
  function factorFraction(text) { const [numerator, denominator = "1"] = String(text).split("/"); return fraction(Number(numerator), Number(denominator)); }
  function clamp(value, minimum, maximum) { return Math.max(minimum, Math.min(maximum, Number(value))); }
  function format(value, digits = 4) { if (!Number.isFinite(value)) return "—"; const rounded = Number(value.toFixed(digits)); return (Object.is(rounded, -0) ? 0 : rounded).toLocaleString("en-GB", { maximumFractionDigits: digits }); }
  function escapeAttribute(value) { return String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); }
  function parseNumber(raw) { const normalized = String(raw).trim().replaceAll(",", ".").replace(/[^0-9eE+.-]/g, ""); return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(normalized) ? Number(normalized) : NaN; }

  function addRowMultiple(matrix, target, source, factorValue) { const result = cloneMatrix(matrix); result[target] = result[target].map((value, column) => add(value, multiply(factorValue, result[source][column]))); return result; }
  function scaleRow(matrix, row, factorValue) { const result = cloneMatrix(matrix); result[row] = result[row].map((value) => multiply(value, factorValue)); return result; }
  function swapRows(matrix, first, second) { const result = cloneMatrix(matrix), temporary = result[first]; result[first] = result[second]; result[second] = temporary; return result; }
  function determinant(matrix) { const values = matrix.map((row) => row.slice(0, 3).map(numeric)); return values[0][0] * (values[1][1] * values[2][2] - values[1][2] * values[2][1]) - values[0][1] * (values[1][0] * values[2][2] - values[1][2] * values[2][0]) + values[0][2] * (values[1][0] * values[2][1] - values[1][1] * values[2][0]); }
  function rowResiduals(matrix) { return matrix.map((row) => add(add(add(multiply(row[0], fraction(SOLUTION[0])), multiply(row[1], fraction(SOLUTION[1]))), multiply(row[2], fraction(SOLUTION[2]))), multiply(row[3], fraction(-1)))); }
  function isReducedSolution(matrix) { const expected = [[1,0,0,4],[0,1,0,3],[0,0,1,5]].map((row) => row.map((value) => fraction(value))); return matrix.every((row, rowIndex) => row.every((value, column) => equal(value, expected[rowIndex][column]))); }

  const guidedOperations = Object.freeze([
    Object.freeze({ label: "R₂ ← R₂ − 2R₁", apply: (matrix) => addRowMultiple(matrix, 1, 0, fraction(-2)) }),
    Object.freeze({ label: "R₃ ← R₃ − R₁", apply: (matrix) => addRowMultiple(matrix, 2, 0, fraction(-1)) }),
    Object.freeze({ label: "R₃ ← 3R₃", apply: (matrix) => scaleRow(matrix, 2, fraction(3)) }),
    Object.freeze({ label: "R₃ ← R₃ + 2R₂", apply: (matrix) => addRowMultiple(matrix, 2, 1, fraction(2)) }),
    Object.freeze({ label: "R₃ ← −(1/11)R₃", apply: (matrix) => scaleRow(matrix, 2, fraction(-1, 11)) }),
    Object.freeze({ label: "R₂ ← R₂ + R₃", apply: (matrix) => addRowMultiple(matrix, 1, 2, fraction(1)) }),
    Object.freeze({ label: "R₂ ← −(1/3)R₂", apply: (matrix) => scaleRow(matrix, 1, fraction(-1, 3)) }),
    Object.freeze({ label: "R₁ ← R₁ − R₂", apply: (matrix) => addRowMultiple(matrix, 0, 1, fraction(-1)) }),
    Object.freeze({ label: "R₁ ← R₁ − R₃", apply: (matrix) => addRowMultiple(matrix, 0, 2, fraction(-1)) }),
  ]);

  function initialState() { return { matrix: initialMatrix(), history: [], guidedProgress: 0, operationType: "add", targetRow: 1, sourceRow: 0, factor: "-2", boardMessage: "Challenge loaded. Every legal row operation changes the displayed equations while preserving their common solution.", stage: 0, xAnswer: "", yAnswer: "", zAnswer: "", feedback: "", feedbackTone: "neutral", committed: false, hintsUsed: 0, revealed: false }; }
  let state = initialState();
  function restoreChallenge() { state.matrix = initialMatrix(); state.history = []; state.guidedProgress = 0; state.operationType = "add"; state.targetRow = 1; state.sourceRow = 0; state.factor = "-2"; state.boardMessage = "Challenge restored: begin with R₂←R₂−2R₁ or choose another legal operation."; }
  function rememberState() { state.history.push({ matrix: cloneMatrix(state.matrix), guidedProgress: state.guidedProgress, message: state.boardMessage }); }

  function stageControlsMarkup() { return `<div class="p231-stage-controls" role="group" aria-label="Linear-system reasoning stages">${stages.map((stage, index) => `<button class="secondary-button ${state.stage === index ? "active" : ""}" type="button" data-problem-action="p231-stage" data-p231-stage="${index}" aria-pressed="${state.stage === index}"><span>${index + 1}</span>${stage.short}</button>`).join("")}</div>`; }
  function stageCaptionMarkup() { const stage = stages[state.stage]; return `<div class="p231-stage-caption"><div><div class="eyebrow">Stage ${state.stage + 1} of 3</div><strong>${stage.title}</strong><p>${stage.copy}</p></div><button class="ghost-button" type="button" data-problem-action="p231-next-stage" ${state.stage >= 2 ? "disabled" : ""}>${state.stage >= 2 ? "Solution isolated" : "Next stage"}</button></div>`; }

  function matrixMarkup() {
    const residuals = rowResiduals(state.matrix), solved = isReducedSolution(state.matrix);
    return `<section class="p231-matrix-card" aria-label="Current augmented matrix"><div class="p231-matrix-heading"><div><span class="eyebrow">Exact augmented matrix</span><strong>${solved ? "Reduced solution form" : "Equivalent system"}</strong></div><span>${state.history.length} operation${state.history.length === 1 ? "" : "s"}</span></div><div class="p231-matrix-wrap"><div class="p231-row-labels" aria-hidden="true"><span>R₁</span><span>R₂</span><span>R₃</span></div><div class="p231-matrix-grid">${state.matrix.flatMap((row, rowIndex) => row.map((value, column) => `<span class="p231-cell ${column === 3 ? "is-augmented" : ""} is-row-${rowIndex + 1}">${fractionText(value)}</span>`)).join("")}</div></div><div class="p231-consistency" aria-live="polite">${residuals.map((residual, index) => `<span class="${residual.n === 0 ? "is-zero" : "is-error"}">R${index + 1} at (4,3,5): ${fractionText(residual)}</span>`).join("")}</div><p data-p231-board-message role="status">${state.boardMessage}</p></section>`;
  }

  function cubeVertices() { return [[0,0,0],[6,0,0],[0,6,0],[6,6,0],[0,0,6],[6,0,6],[0,6,6],[6,6,6]]; }
  const cubeEdges = Object.freeze([[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]]);
  function dot(left, right) { return left[0]*right[0]+left[1]*right[1]+left[2]*right[2]; }
  function cross(left, right) { return [left[1]*right[2]-left[2]*right[1],left[2]*right[0]-left[0]*right[2],left[0]*right[1]-left[1]*right[0]]; }
  function normalise(vector) { const length = Math.sqrt(dot(vector,vector)); return length ? vector.map((value) => value/length) : [1,0,0]; }
  function planePolygon(row) {
    const coefficients = row.slice(0,3).map(numeric), constant = numeric(row[3]), vertices = cubeVertices(), points = [];
    const addPoint = (point) => { if (!points.some((existing) => existing.every((value,index) => Math.abs(value-point[index])<1e-7))) points.push(point); };
    cubeEdges.forEach(([firstIndex,secondIndex]) => { const first=vertices[firstIndex],second=vertices[secondIndex],firstValue=dot(coefficients,first)-constant,secondValue=dot(coefficients,second)-constant;if(Math.abs(firstValue)<1e-9)addPoint(first);if(Math.abs(secondValue)<1e-9)addPoint(second);if(firstValue*secondValue<0){const ratio=firstValue/(firstValue-secondValue);addPoint(first.map((value,index)=>value+ratio*(second[index]-value)));} });
    if(points.length<3)return points;const centre=[0,1,2].map((axis)=>points.reduce((sum,point)=>sum+point[axis],0)/points.length),normal=normalise(coefficients),reference=Math.abs(normal[0])<.8?[1,0,0]:[0,1,0],basisU=normalise(cross(normal,reference)),basisV=cross(normal,basisU);return points.sort((a,b)=>Math.atan2(dot(a.map((v,i)=>v-centre[i]),basisV),dot(a.map((v,i)=>v-centre[i]),basisU))-Math.atan2(dot(b.map((v,i)=>v-centre[i]),basisV),dot(b.map((v,i)=>v-centre[i]),basisU)));
  }
  function project(point) { return [646+(point[0]-point[1])*12,300-point[2]*24+(point[0]+point[1])*6]; }
  function planesSvg() {
    const polygons=state.matrix.map(planePolygon),vertices=cubeVertices(),solutionPoint=project(SOLUTION),residuals=rowResiduals(state.matrix),description=`Three current row planes are shown inside a zero-to-six coordinate cube. Their common point is x 4, y 3, z 5. Substitution residuals are ${residuals.map(fractionText).join(", ")}. Legal row operations may replace individual planes but leave this common intersection unchanged.`;
    return `<svg class="p231-planes p231-stage-${state.stage}" viewBox="0 0 250 360" role="img" aria-labelledby="p231-planes-title p231-planes-desc"><title id="p231-planes-title">Three equivalent row planes with one common solution</title><desc id="p231-planes-desc">${description}</desc><defs><linearGradient id="p231-plane-board" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#172d3b"/><stop offset="1" stop-color="#31283e"/></linearGradient></defs><rect class="p231-plane-board" x="1" y="1" width="248" height="358" rx="18"/><text class="p231-plane-kicker" x="16" y="25">CURRENT ROW PLANES</text><g transform="translate(-520 0)"><g class="p231-cube">${cubeEdges.map(([a,b])=>{const first=project(vertices[a]),second=project(vertices[b]);return `<line x1="${first[0]}" y1="${first[1]}" x2="${second[0]}" y2="${second[1]}"/>`;}).join("")}</g>${polygons.map((polygon,index)=>`<polygon class="p231-plane is-row-${index+1}" points="${polygon.map((point)=>project(point).join(",")).join(" ")}"/>`).join("")}<g class="p231-solution-point"><circle cx="${solutionPoint[0]}" cy="${solutionPoint[1]}" r="7"/><circle cx="${solutionPoint[0]}" cy="${solutionPoint[1]}" r="2"/></g><text class="p231-axis-label" x="${project([6,0,0])[0]+5}" y="${project([6,0,0])[1]+4}">x</text><text class="p231-axis-label" x="${project([0,6,0])[0]-9}" y="${project([0,6,0])[1]+4}">y</text><text class="p231-axis-label" x="${project([0,0,6])[0]+5}" y="${project([0,0,6])[1]}">z</text></g><g class="p231-plane-legend"><text x="16" y="290">COMMON INTERSECTION</text><text class="p231-plane-solution" x="234" y="316" text-anchor="end">(4, 3, 5)</text><text class="p231-plane-note" x="16" y="339">planes can change · intersection cannot</text></g></svg>`;
  }

  function operationControlsMarkup() {
    const guideFinished=state.guidedProgress===guidedOperations.length,guideLost=state.guidedProgress<0,next=guideFinished?null:guidedOperations[state.guidedProgress];
    return `<section class="p231-operations" aria-label="Legal row-operation controls"><div class="p231-operation-tabs" role="group" aria-label="Choose row operation type">${[["add","Add multiple"],["scale","Scale row"],["swap","Swap rows"]].map(([type,label])=>`<button class="secondary-button ${state.operationType===type?"active":""}" type="button" data-problem-action="p231-type" data-p231-type="${type}" aria-pressed="${state.operationType===type}">${label}</button>`).join("")}</div><div class="p231-operation-builder">${state.operationType==="add"?`<label for="p231-target">Target<select id="p231-target" data-p231-select="target">${[0,1,2].map((row)=>`<option value="${row}" ${state.targetRow===row?"selected":""}>R${row+1}</option>`).join("")}</select></label><label for="p231-factor">Multiplier<select id="p231-factor" data-p231-select="factor">${FACTOR_OPTIONS.map((factorValue)=>`<option value="${factorValue}" ${state.factor===factorValue?"selected":""}>${factorValue}</option>`).join("")}</select></label><label for="p231-source">Source<select id="p231-source" data-p231-select="source">${[0,1,2].map((row)=>`<option value="${row}" ${state.sourceRow===row?"selected":""}>R${row+1}</option>`).join("")}</select></label>`:state.operationType==="scale"?`<label for="p231-target">Row<select id="p231-target" data-p231-select="target">${[0,1,2].map((row)=>`<option value="${row}" ${state.targetRow===row?"selected":""}>R${row+1}</option>`).join("")}</select></label><label for="p231-factor">Non-zero scale<select id="p231-factor" data-p231-select="factor">${FACTOR_OPTIONS.map((factorValue)=>`<option value="${factorValue}" ${state.factor===factorValue?"selected":""}>${factorValue}</option>`).join("")}</select></label>`:`<label for="p231-target">First row<select id="p231-target" data-p231-select="target">${[0,1,2].map((row)=>`<option value="${row}" ${state.targetRow===row?"selected":""}>R${row+1}</option>`).join("")}</select></label><label for="p231-source">Second row<select id="p231-source" data-p231-select="source">${[0,1,2].map((row)=>`<option value="${row}" ${state.sourceRow===row?"selected":""}>R${row+1}</option>`).join("")}</select></label>`}<button class="primary-button" type="button" data-problem-action="p231-apply">Apply legal operation</button></div><div class="p231-guide-row"><button class="secondary-button" type="button" data-problem-action="p231-guide" ${guideFinished?"disabled":""}>${guideFinished?"Guide complete":guideLost?"Restore guided elimination":`Next guide: ${next.label}`}</button><button class="ghost-button" type="button" data-problem-action="p231-undo" ${state.history.length?"":"disabled"}>Undo</button><button class="ghost-button" type="button" data-problem-action="p231-restore">Restore challenge</button></div><button class="p231-illegal-button" type="button" data-problem-action="p231-illegal">Why can’t I edit just one entry?</button></section>`;
  }

  function dynamicMarkup() { return `<div class="p231-dynamic"><div class="p231-lab-grid">${matrixMarkup()}${planesSvg()}</div>${operationControlsMarkup()}</div>`; }
  function feedbackMarkup() { return state.feedback ? `<div class="math2-feedback is-${state.feedbackTone}" role="status">${state.feedback}</div>` : ""; }
  function hintsMarkup() { return state.hintsUsed ? `<div class="hint-stack p231-hints" aria-live="polite">${hints.slice(0,state.hintsUsed).map((hint,index)=>`<div class="hint"><strong>Hint ${index+1}.</strong> ${hint}</div>`).join("")}</div>` : ""; }
  function solutionMarkup() {
    if(!state.revealed)return "";
    return `<section class="p231-solution" aria-labelledby="p231-solution-heading"><h3 id="p231-solution-heading" tabindex="-1">Eliminate one variable column at a time</h3><p>Begin with the augmented matrix and remove x below the first pivot:</p><div class="p231-equation">R₂←R₂−2R₁ gives [0,−3,−1|−14]<br>R₃←R₃−R₁ gives [0,2,−3|−9].</div><p>Eliminating y from those rows produces a row proportional to [0,0,−11|−55], so</p><div class="p231-equation">−11z=−55, hence z=5.</div><p>Back-substitution then gives</p><div class="p231-equation">−3y−z=−14 ⇒ y=3,<br>x+y+z=12 ⇒ x=4.</div><div class="p231-equation is-answer"><strong>(x,y,z)=(4,3,5).</strong></div><p>Check: 4+3+5=12; 2(4)−3+5=10; and 4+3(3)−2(5)=3. Every legal row operation acts on a whole equation and preserves this common solution. Editing one isolated matrix entry changes an equation and can move or destroy the intersection.</p></section>`;
  }

  function snapshot() { const residuals=rowResiduals(state.matrix);return JSON.stringify({problem:PROBLEM,provenance:EXTENSION_DISCLOSURE,variableOrder:["x","y","z"],originalSystem:["x+y+z=12","2x-y+z=10","x+3y-2z=3"],currentAugmentedMatrixExact:state.matrix.map((row)=>row.map(fractionText)),currentAugmentedMatrixNumeric:state.matrix.map((row)=>row.map(numeric)),legalOperations:["swap two rows","multiply an entire row by a non-zero scalar","add a scalar multiple of one row to another"],illegalEditWarning:"changing one isolated entry changes an equation and need not preserve the solution set",solution:SOLUTION,rowResidualsAtSolution:residuals.map(fractionText),allRowsContainSolution:residuals.every((value)=>value.n===0),coefficientDeterminant:determinant(state.matrix),reducedSolutionForm:isReducedSolution(state.matrix),guidedProgress:state.guidedProgress,guidedSteps:guidedOperations.length,historyLength:state.history.length,operationBuilder:{type:state.operationType,targetRow:state.targetRow+1,sourceRow:state.sourceRow+1,factor:state.factor},stage:state.stage+1,answers:{x:state.xAnswer||null,y:state.yAnswer||null,z:state.zAnswer||null},committed:state.committed,hintsUsed:state.hintsUsed,solutionRevealed:state.revealed},null,2); }

  function render() { return `<main class="book-shell p231-shell">${warning()}<header class="book-header"><div class="book-brand"><strong>Linear Algebra and Transformations</strong><span class="eyebrow">Chapter 23 · linear systems</span></div><div class="book-progress">${problemProgress(PROBLEM)}</div>${problemHeaderActions(PROBLEM,resetMarkup)}</header><div class="book-spread p231-spread"><article class="book-page p231-problem-page"><div class="problem-number">Problem 23.1</div><h1 class="book-title p231-title">The Three-Lantern Switchboard</h1><div class="difficulty" aria-label="One star difficulty">★</div><p class="p231-extension-note">${EXTENSION_DISCLOSURE}</p><p class="problem-copy">Three lantern settings x, y and z obey</p><div class="p231-equations"><span>x+y+z=12</span><span>2x−y+z=10</span><span>x+3y−2z=3</span></div><p class="problem-copy"><strong>Find x, y and z.</strong></p><section class="p231-question-card"><strong>Operate on equations, not isolated numbers</strong><p>An augmented-matrix row represents one whole equation. Legal row operations preserve the common solution set.</p></section></article><section class="book-page book-stage p231-stage" aria-labelledby="p231-stage-heading">${stageControlsMarkup()}<div class="p231-stage-heading"><div><span class="eyebrow">Row-operation laboratory</span><h2 id="p231-stage-heading">Change the equations without changing their answer</h2></div><p>Use the guided route or build legal operations, and watch the three planes retain one common point.</p></div>${dynamicMarkup()}${stageCaptionMarkup()}</section><aside class="book-page book-coach p231-coach"><div class="coach-kicker">Set the lanterns</div><p class="coach-question">Enter the three settings for the fixed challenge.</p><form class="p231-answer-form" data-p231-answer-form novalidate><div><label for="p231-x">x</label><input id="p231-x" type="text" inputmode="decimal" autocomplete="off" value="${escapeAttribute(state.xAnswer)}"/></div><div><label for="p231-y">y</label><input id="p231-y" type="text" inputmode="decimal" autocomplete="off" value="${escapeAttribute(state.yAnswer)}"/></div><div><label for="p231-z">z</label><input id="p231-z" type="text" inputmode="decimal" autocomplete="off" value="${escapeAttribute(state.zAnswer)}"/></div><button class="primary-button" type="submit">Check solution</button></form>${feedbackMarkup()}<div class="button-row p231-help-row"><button class="secondary-button" type="button" data-problem-action="p231-hint" ${state.hintsUsed>=hints.length?"disabled":""}>${state.hintsUsed?"Another hint":"Give me a hint"}</button><button class="ghost-button" type="button" data-problem-action="p231-reveal" ${state.revealed?"disabled":""}>${state.revealed?"Solution revealed":"Reveal solution"}</button></div>${hintsMarkup()}${solutionMarkup()}<div class="p231-debug">${debugPanel("Development state",snapshot())}</div></aside></div>${problemNav(PROBLEM)}</main>`; }

  function focusSelector(active){if(!active)return "";if(active.id)return `#${active.id}`;if(active.dataset?.problemAction)return `[data-problem-action="${active.dataset.problemAction}"]`;return "";}
  function updateDynamicDom(){const root=document.querySelector(".p231-shell");if(!root)return;const dynamic=root.querySelector(".p231-dynamic"),selector=dynamic?.contains(document.activeElement)?focusSelector(document.activeElement):"";if(dynamic)dynamic.outerHTML=dynamicMarkup();root.querySelectorAll(".state-surface").forEach((surface)=>{surface.textContent=snapshot();});if(selector){const replacement=root.querySelector(selector);if(replacement){try{replacement.focus({preventScroll:true});}catch(_error){replacement.focus();}}}}
  function renderAndFocus(renderApp,selector){renderApp();window.requestAnimationFrame(()=>document.querySelector(selector)?.focus());}
  function bind({render:renderApp}){
    const root=document.querySelector(".p231-shell");
    root?.addEventListener("click",(event)=>{const control=event.target.closest("[data-problem-action]");if(!control)return;const action=control.dataset.problemAction;
      if(action==="p231-reset"){state=initialState();renderAndFocus(renderApp,"[data-problem-action='p231-guide']");return;}
      if(action==="p231-stage"){state.stage=clamp(Number(control.dataset.p231Stage),0,2);renderAndFocus(renderApp,`[data-p231-stage="${state.stage}"]`);return;}
      if(action==="p231-next-stage"){state.stage=Math.min(2,state.stage+1);renderAndFocus(renderApp,`[data-p231-stage="${state.stage}"]`);return;}
      if(action==="p231-type"){state.operationType=["add","scale","swap"].includes(control.dataset.p231Type)?control.dataset.p231Type:"add";updateDynamicDom();return;}
      if(action==="p231-apply"){if(state.sourceRow===state.targetRow&&state.operationType!=="scale"){state.boardMessage="Choose two different rows. A row cannot be added to or swapped with itself in this builder.";updateDynamicDom();return;}rememberState();const factorValue=factorFraction(state.factor);if(state.operationType==="add")state.matrix=addRowMultiple(state.matrix,state.targetRow,state.sourceRow,factorValue);else if(state.operationType==="scale")state.matrix=scaleRow(state.matrix,state.targetRow,factorValue);else state.matrix=swapRows(state.matrix,state.targetRow,state.sourceRow);state.guidedProgress=-1;state.boardMessage="Legal operation applied. The row planes changed, and (4,3,5) still gives residual zero in every row.";updateDynamicDom();return;}
      if(action==="p231-guide"){if(state.guidedProgress<0){restoreChallenge();updateDynamicDom();return;}if(state.guidedProgress>=guidedOperations.length)return;rememberState();const operation=guidedOperations[state.guidedProgress];state.matrix=operation.apply(state.matrix);state.guidedProgress+=1;state.boardMessage=`Applied ${operation.label}. ${state.guidedProgress===guidedOperations.length?"The matrix now reads x=4, y=3, z=5.":"The solution set is unchanged."}`;updateDynamicDom();return;}
      if(action==="p231-undo"){const previous=state.history.pop();if(previous){state.matrix=previous.matrix;state.guidedProgress=previous.guidedProgress;state.boardMessage=`Undid the last operation. ${previous.message}`;}updateDynamicDom();return;}
      if(action==="p231-restore"){restoreChallenge();updateDynamicDom();return;}
      if(action==="p231-illegal"){state.boardMessage="Editing one cell is not a row operation: it changes one coefficient or constant without applying the same algebra to an entire equation, so the solution set need not survive.";updateDynamicDom();return;}
      if(action==="p231-hint")state.hintsUsed=Math.min(hints.length,state.hintsUsed+1);if(action==="p231-reveal"){state.revealed=true;state.stage=2;restoreChallenge();}renderApp();if(action==="p231-reveal")window.requestAnimationFrame(()=>document.querySelector("#p231-solution-heading")?.focus());
    });
    root?.addEventListener("change",(event)=>{const field=event.target.dataset?.p231Select;if(!field)return;if(field==="target")state.targetRow=clamp(Number(event.target.value),0,2);if(field==="source")state.sourceRow=clamp(Number(event.target.value),0,2);if(field==="factor")state.factor=FACTOR_OPTIONS.includes(event.target.value)?event.target.value:"1";updateDynamicDom();});
    root?.addEventListener("input",(event)=>{if(event.target.matches("#p231-x")){state.xAnswer=event.target.value.slice(0,16);state.feedback="";state.committed=false;}if(event.target.matches("#p231-y")){state.yAnswer=event.target.value.slice(0,16);state.feedback="";state.committed=false;}if(event.target.matches("#p231-z")){state.zAnswer=event.target.value.slice(0,16);state.feedback="";state.committed=false;}});
    root?.querySelector("[data-p231-answer-form]")?.addEventListener("submit",(event)=>{event.preventDefault();const values=["x","y","z"].map((name)=>parseNumber(event.currentTarget.querySelector(`#p231-${name}`)?.value||""));[state.xAnswer,state.yAnswer,state.zAnswer]=["x","y","z"].map((name)=>String(event.currentTarget.querySelector(`#p231-${name}`)?.value||"").trim());state.feedbackTone="warn";state.committed=false;if(values.some((value)=>!Number.isFinite(value)))state.feedback="Enter all three numerical settings.";else if(values.some((value,index)=>Math.abs(value-SOLUTION[index])>.001))state.feedback="Substitute your triple into all three equations, or continue the guided row reduction.";else{state.feedbackTone="success";state.feedback="Correct: (x,y,z)=(4,3,5) satisfies all three equations.";state.committed=true;state.stage=2;restoreChallenge();}renderAndFocus(renderApp,"#p231-x");});
  }

  window.poveyProblemPages[PROBLEM]={render,bind};
}());
